name: hello_world_app
description: A cross-platform app that runs hello world binaries
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/android/
    - assets/linux/
  
  module:
    androidX: true
    androidPackage: com.example.hello_world
    iosBundleIdentifier: com.example.helloWorld
