name: hello_world_app
description: A cross-platform app that runs hello world binaries

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11

flutter:
  uses-material-design: true
  assets:
    - assets/android/
    - assets/linux/
