name: Build and Deliver

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.13.9"
  NDK_VERSION: "r25b"
  GO_VERSION: "1.21.6"

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show initial structure
        run: |
          echo "Initial directory structure:"
          tree -L 3

      - name: Setup Java
        if: matrix.platform == 'android'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
          components: rustfmt, clippy

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Android NDK
        if: matrix.platform == 'android'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          link-to-sdk: true

      - name: Build Binaries
        run: |
          echo "=== BUILDING BINARIES FOR ${{ matrix.platform }} ==="
          cd binaries
          
          if [ "${{ matrix.platform }}" = "android" ]; then
            export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang
            export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang++
            
            # Build C/C++
            $CC c/hello.c -o c/hello-c
            $CXX cpp/hello.cpp -o cpp/hello-cpp
            
            # Build Rust
            cd rust
            cargo build --release --target aarch64-linux-android
            cp target/aarch64-linux-android/release/hello-rust ../
            cd ..
            
            # Build Go
            export CGO_ENABLED=1 GOOS=android GOARCH=arm64
            cd go
            go build -o hello-go hello.go
            cd ..
          else
            # Build Linux binaries
            gcc c/hello.c -o c/hello-c
            g++ cpp/hello.cpp -o cpp/hello-cpp
            cd rust
            cargo build --release
            cp target/release/hello-rust ../
            cd ..
            cd go
            GOOS=linux GOARCH=amd64 go build -o hello-go hello.go
            cd ..
          fi
          
          echo "Final binaries structure:"
          tree -L 3

      - name: Prepare Assets
        run: |
          echo "=== PREPARING ASSETS ==="
          mkdir -p flutter_app/assets/${{ matrix.platform }}
          cp binaries/c/hello-c flutter_app/assets/${{ matrix.platform }}/
          cp binaries/cpp/hello-cpp flutter_app/assets/${{ matrix.platform }}/
          cp binaries/rust/hello-rust flutter_app/assets/${{ matrix.platform }}/
          cp binaries/go/hello-go flutter_app/assets/${{ matrix.platform }}/
          echo "Assets directory:"
          tree flutter_app/assets/

      - name: Configure Linux Desktop
        if: matrix.platform == 'linux'
        run: |
          echo "=== CONFIGURING LINUX DESKTOP ==="
          cd flutter_app
          flutter create --platforms=linux .
          echo "Linux configuration:"
          tree linux -L 3

      - name: Build Flutter App
        run: |
          echo "=== BUILDING FLUTTER APP ==="
          cd flutter_app
          flutter pub get
          
          if [ "${{ matrix.platform }}" = "android" ]; then
            flutter build apk --release --verbose
          else
            flutter build linux --release --verbose \
              --target=lib/main.dart \
              --target-platform=linux-x64 \
              --dart-define=FLUTTER_WEB_USE_SKIA=true
          fi
          
          echo "Build output structure:"
          tree build -L 3

      - name: Package Artifacts
        run: |
          echo "=== PACKAGING ARTIFACTS ==="
          mkdir -p artifacts
          
          if [ "${{ matrix.platform }}" = "android" ]; then
            cp flutter_app/build/app/outputs/apk/release/app-release.apk artifacts/hello_world.apk
          else
            cd flutter_app/build/linux/x64/release/bundle
            zip -r ../../../../../artifacts/linux-app.zip .
            cd -
          fi
          
          echo "Final artifacts:"
          tree artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-deliverables
          path: |
            artifacts/hello_world.apk
            artifacts/linux-app.zip
          if-no-files-found: error
